/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Pagination: typeof import('./components/Pagination.vue')['default']
    PokemonAbility: typeof import('./components/PokemonAbility.vue')['default']
    PokemonCard: typeof import('./components/PokemonCard.vue')['default']
    PokemonTypes: typeof import('./components/PokemonTypes.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
